### ISSUE TITLE
Condition

### ISSUE THREAD

**Issue by Gondee** [gazbert/bxbot-ui#1]
Hey gazbert! I have been using your bxbot a bit now (Still planning on giving you a couple exchange adapters :) ). Just want to know the status of this project (or if you needed any assistance) 

Best,
Joshua

**Comment by gazbert** [comment]
Hey Josh, the project is still alive and kicking :-) 

I'm currently working on the Angular app for administering the bot.
The [BX-bot](https://github.com/gazbert/bxbot) REST API will need dialling in a bit and securing as part of this work too.

Exchange adapters are always welcome - just grab a ticket and go for it! 
Give me a shout if you need anything.

Cheers
Gareth

**Comment by gazbert** [comment]
Closing - project is still active.
